server:
  port: 3000

session:
  name: connect.sid
  cookie:
    path: /
    httpOnly: true
    secure: false
    maxAge: null
  secret: secret

db:
  host: 127.0.0.1
  port: 27017
  name: db_name
  user: db_user
  pass: db_pass

twitter:
  consumerKey: twitter API consumer key
  consumerSecret: twitter API consumer secret
  callbackURL: twitter API Auth Callback URL

admin:
  twitter: twitter id number for admin user (not screen name)
  limited: true
